### PR TITLE
Css refactor

### PR DESCRIPTION
**Pull request by Tobin-jn**
Went through the whole CSS file, let me know if anything looks in need of adjustment. Also first time trying out SMACSS...

### CODE REVIEW

**Comment by Tobin-jn** [comment]
I made this pull request just a couple minutes after yours, yours wasn't up when I pulled down the master to merge locally. Little conflict in the CSS. We just need as I moved the fonts around.
.container {
 display: flex;
flex-direction: column;
}

**Review by marcusp619 — APPROVED** [review]
Fixed merge conflicts nothing serious

**Review by marcusp619 — CHANGES_REQUESTED** [review]
we still need to fix the header

**Comment by marcusp619** [comment]
Still, need to fix the height of the search input.

**Pull request merged**
